### ISSUE TITLE
prevent console window from automatic exit after task achieved

### ISSUE THREAD

**Issue by khushi0704** [khushi0704/UserLogin-system#2]

**Comment by mukul-kr** [comment]
you can just take user input for freezing the console --- like after this
```
UserLogin app;
app.check_file();
app.login();
```
you can add this
```
char freezing_terminal;
cin>>freezing_terminal;
```
Hope this will do the job

**Comment by khushi0704** [comment]
yes @Clash-ion I've added this code , thanks for the suggestion !
