### ISSUE TITLE
This program can eaisly be bruteforced

### ISSUE THREAD

**Issue by mukul-kr** [khushi0704/UserLogin-system#5]
On line 53 `while(!access)` will give user unlimited attempt to any user, and this can be used in bad ways if someone writes a script which input value into your program.
Easy way to avoid this is by giving user limited attempts(take 10 for example).
Now you can simply close the program or make a log of all input in one file with their time. And from the last attempt i.e. 10th attempt make it like user have reached maximum no of input and you can then give permission to get another attempt at that login in one day or so, I mean this is what is used in major apps.

**Comment by khushi0704** [comment]
@Clash-ion yes , thanks for reminding me that ! I totally forgot about it , though I intended to do that after some time later maybe , but anyways thanks .
